version: "2"
services:
  postgres:
    image: postgres
  redis:
    image: redis:alpine
  api:
    build: .
    ports:
      - "8080"
    links:
      - database
    logging:
      driver: "json-file"
    environment:
      RESOLVERS: "8.8.8.8 8.8.4.4"
      COSY_PREFIX: /usr/local
      COSY_HOST: api:8080
      COSY_BRANCH: ${COSY_BRANCH}
      POSTGRES_HOST: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ""
      POSTGRES_DATABASE: postgres
      AUTH0_DOMAIN: ${AUTH0_DOMAIN}
      AUTH0_ID: ${AUTH0_ID}
      AUTH0_SECRET: ${AUTH0_SECRET}
      AUTH0_TOKEN: ${AUTH0_TOKEN}
      DOCKER_USER: ${DOCKER_USER}
      DOCKER_SECRET: ${DOCKER_SECRET}
